language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t arpitarora/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true arpitarora/docker-react npm run test